# Generated by Django 5.2.4 on 2025-11-27 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("eventos", "0001_initial"),
        ("interessados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusInscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                (
                    "cor",
                    models.CharField(
                        default="#6c757d",
                        help_text="Código hexadecimal da cor (ex: #28a745)",
                        max_length=7,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Status de Inscrição",
                "verbose_name_plural": "Status de Inscrições",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes",
                        to="eventos.evento",
                    ),
                ),
                (
                    "interessado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes",
                        to="interessados.interessado",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes",
                        to="selecao.statusinscricao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscrição",
                "verbose_name_plural": "Inscrições",
                "ordering": ["-data_inscricao"],
                "unique_together": {("interessado", "evento")},
            },
        ),
        migrations.CreateModel(
            name="Classificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posicao", models.PositiveIntegerField()),
                (
                    "pontuacao_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "classificado",
                    models.BooleanField(
                        default=False,
                        help_text="Se foi classificado dentro das vagas disponíveis",
                    ),
                ),
                (
                    "lista_espera",
                    models.BooleanField(
                        default=False, help_text="Se está na lista de espera"
                    ),
                ),
                ("processado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "inscricao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classificacao",
                        to="selecao.inscricao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classificação",
                "verbose_name_plural": "Classificações",
                "ordering": ["inscricao__evento", "posicao"],
                "unique_together": {("inscricao",)},
            },
        ),
        migrations.CreateModel(
            name="InscricaoCriterioAtendido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pontos_atribuidos", models.PositiveIntegerField()),
                (
                    "validado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se critério customizado foi validado manualmente",
                    ),
                ),
                ("observacao_validacao", models.TextField(blank=True)),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes_atendidas",
                        to="eventos.criterio",
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios_atendidos",
                        to="selecao.inscricao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério Atendido",
                "verbose_name_plural": "Critérios Atendidos",
                "ordering": ["inscricao", "-pontos_atribuidos"],
                "unique_together": {("inscricao", "criterio")},
            },
        ),
    ]
