# Generated by Django 5.2.4 on 2025-12-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selecao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificacao",
            name="posicao",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
