# Generated by Django 5.2.4 on 2026-05-20 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selecao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificacao",
            name="pontuacao_total",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="classificacao",
            name="posicao",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
