# Generated by Django 5.2.4 on 2026-06-23 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selecao", "0002_alter_classificacao_pontuacao_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscricao",
            name="data_inscricao",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
