# Generated by Django 5.2.4 on 2025-12-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selecao", "0002_alter_classificacao_posicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusinscricao",
            name="descricao",
            field=models.TextField(blank=True, default=""),
        ),
    ]
