# Generated by Django 5.2.4 on 2025-12-05 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("selecao", "0003_statusinscricao_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statusinscricao",
            name="descricao",
        ),
    ]
