site_name: Documentação - Sistema MetaReciclagem
site_description: Documentação técnica completa
theme:
  name: material
  language: pt
  palette:
    primary: indigo
    accent: indigo

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist
  - mermaid2

plugins:
  - search
  - mermaid2

nav:
  - Início: index.md
  - Para Começar: 01-comcar.md
  - Arquitetura: 02-arquitetura.md
  - Componentes: 03-componentes.md
  - Fluxos: 04-fluxos.md
  - Banco de Dados: 05-banco-dados.md
  - Setup Dev: 06-setup.md
  - Deploy: 07-deploy.md
  - Glossário: 10-glossario.md