# Generated by Django 5.2.4 on 2026-01-26 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interessado",
            name="cep",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Somente números (8 dígitos)",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CEP deve conter exatamente 8 dígitos", regex="^\\d{8}$"
                    )
                ],
                verbose_name="CEP",
            ),
        ),
        migrations.AddField(
            model_name="interessado",
            name="raca_cor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Não informado"),
                    ("BRANCA", "Branca"),
                    ("PRETA", "Preta"),
                    ("PARDA", "Parda"),
                    ("AMARELA", "Amarela"),
                    ("INDIGENA", "Indígena"),
                ],
                default="",
                help_text="Autodeclaração de raça/cor (IBGE)",
                max_length=20,
                verbose_name="Raça/Cor",
            ),
        ),
    ]
