# Generated by Django 5.2.4 on 2025-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interessado",
            name="escolaridade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FUNDAMENTAL_INCOMPLETO", "Ensino Fundamental Incompleto"),
                    ("FUNDAMENTAL_COMPLETO", "Ensino Fundamental Completo"),
                    ("MEDIO_INCOMPLETO", "Ensino Médio Incompleto"),
                    ("MEDIO_COMPLETO", "Ensino Médio Completo"),
                    ("SUPERIOR_INCOMPLETO", "Ensino Superior Incompleto"),
                    ("SUPERIOR_COMPLETO", "Ensino Superior Completo"),
                    ("POS_GRADUACAO", "Pós-Graduação"),
                ],
                default="",
                help_text="Nível de escolaridade do interessado",
                max_length=30,
                verbose_name="Escolaridade",
            ),
        ),
        migrations.AddField(
            model_name="interessado",
            name="rg",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número do RG ou documento de identidade",
                max_length=20,
                verbose_name="RG/Identidade",
            ),
        ),
    ]
