# Generated by Django 5.2.4 on 2025-12-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0002_interessado_escolaridade_interessado_rg"),
    ]

    operations = [
        migrations.AddField(
            model_name="interessado",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o interessado está ativo no sistema",
                verbose_name="Ativo",
            ),
        ),
    ]
