# Generated by Django 5.2.4 on 2026-01-28 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0002_interessado_cep_interessado_raca_cor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interessado",
            name="raca_cor",
        ),
    ]
