# Generated by Django 5.2.4 on 2025-12-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0003_interessado_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="interessado",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o interessado pode acessar o admin (normalmente False)",
                verbose_name="Membro da Equipe",
            ),
        ),
        migrations.AddField(
            model_name="interessado",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o interessado tem todas as permissões (normalmente False)",
                verbose_name="Superusuário",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o interessado pode fazer login no sistema",
                verbose_name="Ativo",
            ),
        ),
    ]
