# Generated by Django 5.2.4 on 2026-02-20 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0003_remove_interessado_raca_cor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token seguro gerado via secrets.token_urlsafe(32)",
                        max_length=100,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "expira_em",
                    models.DateTimeField(
                        help_text="Data/hora de expiração do token (30 minutos após criação)",
                        verbose_name="Expira em",
                    ),
                ),
                (
                    "usado",
                    models.BooleanField(
                        default=False,
                        help_text="True após o token ser utilizado para redefinir a senha",
                        verbose_name="Usado",
                    ),
                ),
                (
                    "interessado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_tokens",
                        to="interessados.interessado",
                        verbose_name="Interessado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Recuperação de Senha",
                "verbose_name_plural": "Tokens de Recuperação de Senha",
                "ordering": ["-criado_em"],
            },
        ),
    ]
