# Generated by Django 5.2.4 on 2026-02-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0005_interessado_must_change_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interessado",
            name="email",
            field=models.EmailField(
                blank=True,
                default=None,
                help_text="E-mail opcional — mas único quando informado",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
    ]
