# Generated by Django 5.2.4 on 2026-03-13 15:59

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0006_alter_interessado_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interessado",
            name="cpf",
            field=encrypted_model_fields.fields.EncryptedCharField(
                help_text="Somente números (11 dígitos) - CRIPTOGRAFADO",
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CPF deve conter exatamente 11 dígitos",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="num_nis",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Número de Identificação Social (11 a 15 dígitos) - CRIPTOGRAFADO",
                validators=[
                    django.core.validators.RegexValidator(
                        message="NIS deve conter entre 11 e 15 dígitos",
                        regex="^\\d{11,15}$",
                    )
                ],
                verbose_name="Número NIS",
            ),
        ),
    ]
