# Generated by Django 5.2.4 on 2026-03-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0007_alter_interessado_cpf_alter_interessado_num_nis"),
    ]

    operations = [
        # PASSO 1: Adiciona o campo SEM unique=True
        # O unique será adicionado na migration 0009, após popular os hashes
        migrations.AddField(
            model_name="interessado",
            name="cpf_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 do CPF — gerado automaticamente, não editar",
                max_length=64,
                verbose_name="Hash do CPF",
            ),
        ),
    ]

    