# Generated by Django 5.2.4 on 2026-03-17 16:38

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0009_interessado_cpf_hash_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="interessado",
            name="consentimento_lgpd",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o interessado aceitou o termo de consentimento",
                verbose_name="Consentimento LGPD",
            ),
        ),
        migrations.AddField(
            model_name="interessado",
            name="consentimento_lgpd_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora em que o interessado aceitou o termo",
                null=True,
                verbose_name="Data do Consentimento",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="celular",
            field=models.CharField(
                blank=True,
                default="",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefone deve conter 10 ou 11 dígitos",
                        regex="^\\d{10,11}$",
                    )
                ],
                verbose_name="Celular",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="cep",
            field=models.CharField(
                blank=True,
                default="",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CEP deve conter exatamente 8 dígitos", regex="^\\d{8}$"
                    )
                ],
                verbose_name="CEP",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="email",
            field=models.EmailField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="escolaridade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FUNDAMENTAL_INCOMPLETO", "Ensino Fundamental Incompleto"),
                    ("FUNDAMENTAL_COMPLETO", "Ensino Fundamental Completo"),
                    ("MEDIO_INCOMPLETO", "Ensino Médio Incompleto"),
                    ("MEDIO_COMPLETO", "Ensino Médio Completo"),
                    ("SUPERIOR_INCOMPLETO", "Ensino Superior Incompleto"),
                    ("SUPERIOR_COMPLETO", "Ensino Superior Completo"),
                    ("POS_GRADUACAO", "Pós-Graduação"),
                ],
                default="",
                max_length=30,
                verbose_name="Escolaridade",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Membro da Equipe"),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Superusuário"),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Último Login"
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="must_change_password",
            field=models.BooleanField(
                default=False, verbose_name="Deve trocar a senha"
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="num_nis",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Número de Identificação Social - CRIPTOGRAFADO",
                validators=[
                    django.core.validators.RegexValidator(
                        message="NIS deve conter entre 11 e 15 dígitos",
                        regex="^\\d{11,15}$",
                    )
                ],
                verbose_name="Número NIS",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="rg",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="RG/Identidade"
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="telefone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefone deve conter 10 ou 11 dígitos",
                        regex="^\\d{10,11}$",
                    )
                ],
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="uf_nascimento",
            field=models.CharField(
                blank=True,
                default="",
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        message="UF deve conter 2 letras maiúsculas", regex="^[A-Z]{2}$"
                    )
                ],
                verbose_name="UF Nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="uf_residencia",
            field=models.CharField(
                blank=True,
                default="",
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        message="UF deve conter 2 letras maiúsculas", regex="^[A-Z]{2}$"
                    )
                ],
                verbose_name="UF Residência",
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expira_em",
            field=models.DateTimeField(verbose_name="Expira em"),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(max_length=100, unique=True, verbose_name="Token"),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="usado",
            field=models.BooleanField(default=False, verbose_name="Usado"),
        ),
    ]
