# Generated by Django 5.2.4 on 2026-03-18 18:34

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0010_interessado_consentimento_lgpd_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="interessado",
            name="consentimento_lgpd",
            field=models.BooleanField(default=False, verbose_name="Consentimento LGPD"),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="consentimento_lgpd_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data do Consentimento"
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="cpf",
            field=encrypted_model_fields.fields.EncryptedCharField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CPF deve conter exatamente 11 dígitos",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="cpf_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                unique=True,
                verbose_name="Hash do CPF",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="num_nis",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                default="",
                validators=[
                    django.core.validators.RegexValidator(
                        message="NIS deve conter entre 11 e 15 dígitos",
                        regex="^\\d{11,15}$",
                    )
                ],
                verbose_name="Número NIS",
            ),
        ),
        migrations.AlterField(
            model_name="interessado",
            name="senha",
            field=models.CharField(max_length=128, verbose_name="Senha"),
        ),
        migrations.CreateModel(
            name="SolicitacaoExclusao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_solicitante",
                    models.CharField(max_length=50, verbose_name="Nome do Solicitante"),
                ),
                (
                    "email_solicitante",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="E-mail do Solicitante",
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Motivo informado pelo interessado (opcional)",
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADA", "Aprovada"),
                            ("RECUSADA", "Recusada"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "solicitado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Solicitado em"
                    ),
                ),
                (
                    "analisado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Analisado em"
                    ),
                ),
                (
                    "parecer_staff",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Motivo da aprovação ou recusa",
                        verbose_name="Parecer do Staff",
                    ),
                ),
                (
                    "analisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Analisado por",
                    ),
                ),
                (
                    "interessado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_exclusao",
                        to="interessados.interessado",
                        verbose_name="Interessado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Exclusão",
                "verbose_name_plural": "Solicitações de Exclusão",
                "ordering": ["-solicitado_em"],
            },
        ),
    ]
