# Generated by Django 5.2.4 on 2026-04-07 15:34

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interessados", "0011_alter_interessado_consentimento_lgpd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interessado",
            name="cpf",
            field=encrypted_model_fields.fields.EncryptedCharField(
                unique=True, verbose_name="CPF"
            ),
        ),
        migrations.AlterField(
            model_name="sexo",
            name="nome",
            field=models.CharField(max_length=20, unique=True, verbose_name="Sexo"),
        ),
    ]
