# Generated by Django 5.2.4 on 2026-01-15 20:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("eventos", "0001_initial"),
        ("interessados", "0001_initial"),
        ("selecao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusMatricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                (
                    "cor",
                    models.CharField(
                        default="#6c757d",
                        help_text="Código hexadecimal da cor (ex: #007bff)",
                        max_length=7,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Status de Matrícula",
                "verbose_name_plural": "Status de Matrículas",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_matricula",
                    models.CharField(
                        editable=False,
                        help_text="Gerado automaticamente no formato AAAANNN (ex: 2026001)",
                        max_length=10,
                        unique=True,
                        verbose_name="Nº Matrícula",
                    ),
                ),
                (
                    "data_matricula",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Matrícula"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações/Anotações"),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        help_text="Inscrição que originou esta matrícula",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="selecao.inscricao",
                        verbose_name="Inscrição",
                    ),
                ),
                (
                    "interessado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="interessados.interessado",
                        verbose_name="Interessado",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="eventos.turma",
                        verbose_name="Turma",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="academico.statusmatricula",
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "ordering": ["-data_matricula"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nota de 0 a 10",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("10.00")),
                        ],
                        verbose_name="Nota Final",
                    ),
                ),
                (
                    "frequencia",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentual de presença (%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Frequência (%)",
                    ),
                ),
                (
                    "aprovado",
                    models.BooleanField(default=False, verbose_name="Aprovado"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "certificado_emitido",
                    models.BooleanField(
                        default=False, verbose_name="Certificado Emitido"
                    ),
                ),
                (
                    "data_emissao_certificado",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Emissão do Certificado",
                    ),
                ),
                (
                    "avaliado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Avaliado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "matricula",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="academico.matricula",
                        verbose_name="Matrícula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-avaliado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="matricula",
            index=models.Index(
                fields=["numero_matricula"], name="academico_m_numero__4bc01b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matricula",
            index=models.Index(
                fields=["turma", "interessado"], name="academico_m_turma_i_1f9f0d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matricula",
            unique_together={("turma", "interessado")},
        ),
    ]
