# Generated by Django 5.2.4 on 2025-11-27 15:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("eventos", "0001_initial"),
        ("interessados", "0001_initial"),
        ("selecao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusMatricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                (
                    "cor",
                    models.CharField(
                        default="#6c757d",
                        help_text="Código hexadecimal da cor (ex: #007bff)",
                        max_length=7,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Status de Matrícula",
                "verbose_name_plural": "Status de Matrículas",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_matricula", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "inscricao",
                    models.ForeignKey(
                        help_text="Inscrição que originou esta matrícula",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="selecao.inscricao",
                    ),
                ),
                (
                    "interessado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="interessados.interessado",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="eventos.turma",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="academico.statusmatricula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "ordering": ["-data_matricula"],
                "unique_together": {("turma", "interessado")},
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nota de 0 a 10",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("10.00")),
                        ],
                    ),
                ),
                (
                    "frequencia",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentual de presença (%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("aprovado", models.BooleanField(default=False)),
                ("observacoes", models.TextField(blank=True)),
                ("certificado_emitido", models.BooleanField(default=False)),
                ("data_emissao_certificado", models.DateField(blank=True, null=True)),
                ("avaliado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "matricula",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="academico.matricula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-avaliado_em"],
            },
        ),
    ]
