# Generated by Django 5.2.4 on 2026-02-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academico", "0001_initial"),
        ("eventos", "0001_initial"),
        ("interessados", "0005_interessado_must_change_password"),
        ("selecao", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="matricula",
            index=models.Index(
                fields=["inscricao"], name="academico_m_inscric_af84a1_idx"
            ),
        ),
    ]
