# Generated by Django 5.2.4 on 2025-11-27 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Criterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NIS", "Número de Identificação Social (NIS)"),
                            ("PCD", "Pessoa com Deficiência"),
                            ("FOTOTIPO", "Fototipo/Raça"),
                            ("IDADE", "Idade"),
                            ("ORDEM", "Ordem de Inscrição"),
                            ("CUSTOM", "Customizado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "pontos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Pontos atribuídos ao atender este critério",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ordem_idade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CRESCENTE", "Crescente (mais novos primeiro)"),
                            ("DECRESCENTE", "Decrescente (mais velhos primeiro)"),
                        ],
                        help_text="Apenas para critério tipo IDADE",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "requer_validacao_manual",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, critério precisa ser validado manualmente pela equipe",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Critério de Classificação",
                "verbose_name_plural": "Critérios de Classificação",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data_inicio_inscricao", models.DateTimeField()),
                ("data_fim_inscricao", models.DateTimeField()),
                ("data_inicio_evento", models.DateField()),
                ("data_fim_evento", models.DateField()),
                (
                    "total_vagas",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("vagas_disponiveis", models.PositiveIntegerField(editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-data_inicio_inscricao"],
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Status de Evento",
                "verbose_name_plural": "Status de Eventos",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="EventoCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pontos_customizados",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Sobrescreve pontos padrão do critério (opcional)",
                        null=True,
                    ),
                ),
                (
                    "reserva_vagas",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de vagas reservadas para este critério",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evento_criterios",
                        to="eventos.criterio",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evento_criterios",
                        to="eventos.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério do Evento",
                "verbose_name_plural": "Critérios do Evento",
                "ordering": ["evento", "ordem", "criterio__nome"],
                "unique_together": {("evento", "criterio")},
            },
        ),
        migrations.AddField(
            model_name="evento",
            name="criterios",
            field=models.ManyToManyField(
                related_name="eventos",
                through="eventos.EventoCriterio",
                to="eventos.criterio",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventos",
                to="eventos.status",
            ),
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("MATUTINO", "Matutino"),
                            ("VESPERTINO", "Vespertino"),
                            ("NOTURNO", "Noturno"),
                            ("INTEGRAL", "Integral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "capacidade",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("local", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas",
                        to="eventos.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["evento", "nome"],
            },
        ),
    ]
