# Generated by Django 5.2.4 on 2026-01-15 20:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Criterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_criterio",
                    models.CharField(
                        choices=[
                            ("PONTUACAO", "Pontuação"),
                            ("ORDENACAO", "Ordenação"),
                        ],
                        default="PONTUACAO",
                        help_text="Pontuação = soma pontos | Ordenação = define ordem de classificação",
                        max_length=20,
                        verbose_name="Tipo de Critério",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único do critério (ex: PCD, ORDEM_INSCRICAO, IDADE_CRESCENTE)",
                        max_length=30,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome descritivo do critério",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do critério",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "pontos",
                    models.IntegerField(
                        blank=True,
                        help_text="Pontuação (apenas para tipo PONTUACAO)",
                        null=True,
                        verbose_name="Pontos",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("ORDENACAO", "Ordenação"),
                            ("CRONOLÓGICA", "Ordem de Inscrição"),
                            ("IDADE", "Idade"),
                            ("VULNERABILIDADE", "Vulnerabilidade Social"),
                            ("FAIXA_ETARIA", "Faixa Etária"),
                            ("ESCOLARIDADE", "Escolaridade"),
                            ("COTA_RACIAL", "Cota Racial"),
                        ],
                        help_text="Categoria do critério",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Se False, não aparece para seleção",
                        verbose_name="Ativo",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Critério de Classificação",
                "verbose_name_plural": "Critérios de Classificação",
                "ordering": ["categoria", "-pontos", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, unique=True, verbose_name="Nome"),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#6c757d",
                        help_text="Cor em hexadecimal (ex: #007bff)",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(default=0, verbose_name="Ordem de Exibição"),
                ),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Evento"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "total_vagas",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Total de Vagas",
                    ),
                ),
                (
                    "data_inicio_inscricao",
                    models.DateTimeField(verbose_name="Início das Inscrições"),
                ),
                (
                    "data_fim_inscricao",
                    models.DateTimeField(verbose_name="Fim das Inscrições"),
                ),
                (
                    "data_inicio_evento",
                    models.DateField(verbose_name="Início do Evento"),
                ),
                ("data_fim_evento", models.DateField(verbose_name="Fim do Evento")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos",
                        to="eventos.status",
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-data_inicio_evento"],
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Turma"),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("MATUTINO", "Matutino"),
                            ("VESPERTINO", "Vespertino"),
                            ("NOTURNO", "Noturno"),
                            ("INTEGRAL", "Integral"),
                        ],
                        max_length=20,
                        verbose_name="Turno",
                    ),
                ),
                (
                    "capacidade",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Capacidade",
                    ),
                ),
                (
                    "local",
                    models.CharField(blank=True, max_length=200, verbose_name="Local"),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Término")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turmas",
                        to="eventos.evento",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["evento", "nome"],
                "unique_together": {("evento", "nome")},
            },
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="Dia da Semana",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="Horário de Início")),
                ("hora_fim", models.TimeField(verbose_name="Horário de Término")),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="eventos.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário",
                "verbose_name_plural": "Horários",
                "ordering": ["turma", "dia_semana", "hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="EventoCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prioridade",
                    models.IntegerField(
                        default=999,
                        help_text="Ordem de aplicação (1 = primeiro, 2 = segundo, etc.)",
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Critério será usado na classificação?",
                        verbose_name="Ativo",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="eventos.criterio",
                        verbose_name="Critério",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evento_criterios",
                        to="eventos.evento",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério do Evento",
                "verbose_name_plural": "Critérios do Evento",
                "ordering": ["prioridade", "-criterio__pontos", "criterio__nome"],
                "unique_together": {("evento", "criterio")},
            },
        ),
    ]
