# Generated by Django 5.2.4 on 2025-12-02 20:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="criterio",
            options={
                "ordering": ["categoria", "-pontos", "nome"],
                "verbose_name": "Critério de Classificação",
                "verbose_name_plural": "Critérios de Classificação",
            },
        ),
        migrations.AlterModelOptions(
            name="evento",
            options={
                "ordering": ["-data_inicio_evento"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="eventocriterio",
            options={
                "ordering": ["-criterio__pontos", "criterio__nome"],
                "verbose_name": "Critério do Evento",
                "verbose_name_plural": "Critérios do Evento",
            },
        ),
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ["ordem", "nome"],
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
            },
        ),
        migrations.RenameField(
            model_name="turma",
            old_name="atualizada_em",
            new_name="atualizado_em",
        ),
        migrations.RenameField(
            model_name="turma",
            old_name="criada_em",
            new_name="criado_em",
        ),
        migrations.RemoveField(
            model_name="criterio",
            name="ordem_idade",
        ),
        migrations.RemoveField(
            model_name="criterio",
            name="requer_validacao_manual",
        ),
        migrations.RemoveField(
            model_name="criterio",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="criterios",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="vagas_disponiveis",
        ),
        migrations.RemoveField(
            model_name="eventocriterio",
            name="ordem",
        ),
        migrations.RemoveField(
            model_name="eventocriterio",
            name="pontos_customizados",
        ),
        migrations.RemoveField(
            model_name="eventocriterio",
            name="reserva_vagas",
        ),
        migrations.RemoveField(
            model_name="status",
            name="ativo",
        ),
        migrations.RemoveField(
            model_name="status",
            name="descricao",
        ),
        migrations.AddField(
            model_name="criterio",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="criterio",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("VULNERABILIDADE", "Vulnerabilidade Social"),
                    ("FAIXA_ETARIA", "Faixa Etária"),
                    ("ESCOLARIDADE", "Escolaridade"),
                    ("COTA_RACIAL", "Cota Racial"),
                ],
                default="VULNERABILIDADE",
                help_text="Categoria do critério",
                max_length=50,
                verbose_name="Categoria",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="criterio",
            name="codigo",
            field=models.CharField(
                default=1,
                help_text="Código único do critério (ex: PCD, NIS, JOVEM)",
                max_length=30,
                unique=True,
                verbose_name="Código",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="criterio",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventocriterio",
            name="ativo",
            field=models.BooleanField(
                default=True,
                help_text="Critério será usado na classificação?",
                verbose_name="Ativo",
            ),
        ),
        migrations.AddField(
            model_name="eventocriterio",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="status",
            name="cor",
            field=models.CharField(
                default="#6c757d",
                help_text="Cor em hexadecimal (ex: #007bff)",
                max_length=7,
                verbose_name="Cor",
            ),
        ),
        migrations.AlterField(
            model_name="criterio",
            name="ativo",
            field=models.BooleanField(
                default=True,
                help_text="Se False, não aparece para seleção",
                verbose_name="Ativo",
            ),
        ),
        migrations.AlterField(
            model_name="criterio",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Descrição detalhada do critério",
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="criterio",
            name="nome",
            field=models.CharField(
                help_text="Nome descritivo do critério",
                max_length=200,
                verbose_name="Nome",
            ),
        ),
        migrations.AlterField(
            model_name="criterio",
            name="pontos",
            field=models.IntegerField(
                help_text="Pontuação fixa atribuída (NÃO editável após criação)",
                verbose_name="Pontos",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_fim_evento",
            field=models.DateField(verbose_name="Fim do Evento"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_fim_inscricao",
            field=models.DateTimeField(verbose_name="Fim das Inscrições"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_inicio_evento",
            field=models.DateField(verbose_name="Início do Evento"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_inicio_inscricao",
            field=models.DateTimeField(verbose_name="Início das Inscrições"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="nome",
            field=models.CharField(max_length=200, verbose_name="Nome do Evento"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventos",
                to="eventos.status",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="total_vagas",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Total de Vagas",
            ),
        ),
        migrations.AlterField(
            model_name="eventocriterio",
            name="criterio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="eventos.criterio",
                verbose_name="Critério",
            ),
        ),
        migrations.AlterField(
            model_name="eventocriterio",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evento_criterios",
                to="eventos.evento",
                verbose_name="Evento",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="nome",
            field=models.CharField(max_length=50, unique=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="status",
            name="ordem",
            field=models.IntegerField(default=0, verbose_name="Ordem de Exibição"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="capacidade",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Capacidade",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="data_fim",
            field=models.DateField(verbose_name="Data de Término"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="data_inicio",
            field=models.DateField(verbose_name="Data de Início"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turmas",
                to="eventos.evento",
                verbose_name="Evento",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="local",
            field=models.CharField(blank=True, max_length=200, verbose_name="Local"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome da Turma"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="turno",
            field=models.CharField(
                choices=[
                    ("MATUTINO", "Matutino"),
                    ("VESPERTINO", "Vespertino"),
                    ("NOTURNO", "Noturno"),
                    ("INTEGRAL", "Integral"),
                ],
                max_length=20,
                verbose_name="Turno",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="turma",
            unique_together={("evento", "nome")},
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="Dia da Semana",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="Horário de Início")),
                ("hora_fim", models.TimeField(verbose_name="Horário de Término")),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="eventos.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário",
                "verbose_name_plural": "Horários",
                "ordering": ["turma", "dia_semana", "hora_inicio"],
            },
        ),
    ]
