# Generated by Django 5.2.4 on 2025-12-04 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0002_alter_criterio_options_alter_evento_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventocriterio",
            options={
                "ordering": ["evento", "-criterio__pontos"],
                "verbose_name": "Vínculo Evento-Critério",
                "verbose_name_plural": "🔗 VÍNCULOS: Eventos ↔ Critérios",
            },
        ),
    ]
