# Generated by Django 5.2.4 on 2025-12-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0003_alter_eventocriterio_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="modo_classificacao",
            field=models.CharField(
                choices=[
                    ("PONTUACAO", "Por Pontuação (Soma de Critérios)"),
                    ("ORDEM_INSCRICAO", "Por Ordem de Inscrição (Primeiro a chegar)"),
                    ("HIBRIDO", "Híbrido (Cotas + Ordem de Inscrição)"),
                ],
                default="PONTUACAO",
                help_text="Define como os interessados serão classificados neste evento",
                max_length=20,
                verbose_name="Modo de Classificação",
            ),
        ),
    ]
