# Generated by Django 5.2.4 on 2025-12-05 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0004_evento_modo_classificacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventocriterio",
            options={
                "ordering": ["-criterio__pontos", "criterio__nome"],
                "verbose_name": "Critério do Evento",
                "verbose_name_plural": "Critérios do Evento",
            },
        ),
        migrations.RemoveField(
            model_name="evento",
            name="modo_classificacao",
        ),
    ]
