# Generated by Django 5.2.4 on 2025-12-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0005_alter_eventocriterio_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventocriterio",
            options={
                "ordering": ["prioridade", "-criterio__pontos", "criterio__nome"],
                "verbose_name": "Critério do Evento",
                "verbose_name_plural": "Critérios do Evento",
            },
        ),
        migrations.AddField(
            model_name="criterio",
            name="tipo_criterio",
            field=models.CharField(
                choices=[("PONTUACAO", "Pontuação"), ("ORDENACAO", "Ordenação")],
                default="PONTUACAO",
                help_text="Pontuação = soma pontos | Ordenação = define ordem de classificação",
                max_length=20,
                verbose_name="Tipo de Critério",
            ),
        ),
        migrations.AddField(
            model_name="eventocriterio",
            name="prioridade",
            field=models.IntegerField(
                default=999,
                help_text="Ordem de aplicação (1 = primeiro, 2 = segundo, etc.)",
                verbose_name="Prioridade",
            ),
        ),
        migrations.AlterField(
            model_name="criterio",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ORDENACAO", "Ordenação"),
                    ("CRONOLÓGICA", "Ordem de Inscrição"),
                    ("IDADE", "Idade"),
                    ("VULNERABILIDADE", "Vulnerabilidade Social"),
                    ("FAIXA_ETARIA", "Faixa Etária"),
                    ("ESCOLARIDADE", "Escolaridade"),
                    ("COTA_RACIAL", "Cota Racial"),
                ],
                help_text="Categoria do critério",
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="criterio",
            name="codigo",
            field=models.CharField(
                help_text="Código único do critério (ex: PCD, ORDEM_INSCRICAO, IDADE_CRESCENTE)",
                max_length=30,
                unique=True,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="criterio",
            name="pontos",
            field=models.IntegerField(
                blank=True,
                help_text="Pontuação (apenas para tipo PONTUACAO)",
                null=True,
                verbose_name="Pontos",
            ),
        ),
    ]
