# Generated by Django 5.2.4 on 2025-11-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursoseoutros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusInscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=30, unique=True, verbose_name="Status"),
                ),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Status de Inscrição",
                "verbose_name_plural": "Status de Inscrições",
            },
        ),
        migrations.CreateModel(
            name="StatusMatricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=30, unique=True, verbose_name="Status"),
                ),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Status de Matrícula",
                "verbose_name_plural": "Status de Matrículas",
            },
        ),
    ]
