# Generated by Django 5.2.4 on 2025-11-18 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursoseoutros", "0002_statusinscricao_statusmatricula"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ["ordem", "status"],
                "verbose_name": "Status de Evento",
                "verbose_name_plural": "Status de Eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="statusinscricao",
            options={
                "ordering": ["ordem"],
                "verbose_name": "Status de Inscrição",
                "verbose_name_plural": "Status de Inscrições",
            },
        ),
        migrations.AlterModelOptions(
            name="statusmatricula",
            options={
                "ordering": ["ordem"],
                "verbose_name": "Status de Matrícula",
                "verbose_name_plural": "Status de Matrículas",
            },
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="cursoseoutros.statusinscricao",
                verbose_name="Status da Inscrição",
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="cursoseoutros.statusmatricula",
                verbose_name="Status da Matrícula",
            ),
        ),
    ]
