# Generated by Django 5.2.4 on 2026-02-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Se True, o usuário será obrigado a trocar a senha no próximo login",
                verbose_name="Deve trocar a senha",
            ),
        ),
    ]
