# Generated by Django 5.2.4 on 2026-02-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_usuario_must_change_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                help_text="E-mail institucional ou pessoal — obrigatório e único",
                max_length=254,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
    ]
